edition = "2026_pre"
root = "./src"

[dependencies]
bevy_render = { path = "../bevy_render" }
bevy_pbr = { path = "../bevy_pbr" }
bevy_core_pipeline = { path = "../bevy_core_pipeline" }
constants = { path = "../../constants" }
