edition = "2026_pre"
root = "./shaders"

[dependencies]
bevy_render = { path = "../crates/bevy_render" }
bevy_pbr = { path = "../crates/bevy_pbr" }
bevy_core_pipeline = { path = "../crates/bevy_core_pipeline" }
bevy_sprite_render = { path = "../crates/bevy_sprite_render" }
bevy_ui_render = { path = "../crates/bevy_ui_render" }
